name: taxi_break_game
description: "Taxi Break 2D game"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flame: ^1.17.0
  flutter_native_splash: ^2.4.0
  flame_forge2d: ^0.18.0
  flame_tiled: ^1.20.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/cars/
    - assets/images/people/
    - assets/images/environment/
    - assets/tiles/
    - assets/configuration/